fix: due to laravel mix requring webpack and v5.107.0+ breaks due to the missing module of SizeFormatHelpers used by Laravel Mix, we need to lock it down to the last known good version v5.106.2
https://github.com/webpack/webpack/releases#release-v5.107.0

```
[webpack-cli] Error: Cannot find module 'webpack/lib/SizeFormatHelpers'
```